name: ssr
description: Generate Flutter Widgets from server generated json code without any dependency.
version: 0.0.7
homepage: https://ensorta.com
repository: https://github.com/hsbijarniya/ssr

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
